### ISSUE TITLE
Update a trained auto-encoder model with new data

### ISSUE THREAD

**Issue by ziaratnia** [joncox123/Cortexsys#2]
Hello Jonathan

I am Ali a PhD student in University of Tokyo.

Thank you so much for your gear code in Cortexsys project. I want to use your code in my research. And I have a question:

I want to update the trained auto-encoder model with new data. How I can do that in your code?

Can I do that with set the initial weights and biases as the weights and biases that I got from my trained model?

I really appreciate your help.

Regards,
Ali

**Comment by joncox123** [comment]
To do this, simply save nn.W and nn.b. Then, you can load these into some new nnLayers object either when you create it, or afterward.
